language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - mkdir "$HOME/Arduino/libraries/TURIP"
  - mv * "$HOME/Arduino/libraries/TURIP"
script:
  - build_platform uno
  - build_platform leonardo
  - build_platform esp8266
notifications:
  email:
    on_success: change
    on_failure: change
